import './index.css'

export { PersonalCenterLayout } from './Layout'
export { ProfileHome, ProfileSubPage } from './Home'
export { Transactions } from './Transactions'
export { BetHistory } from './BetHistory'
export { Deposit } from './Deposit'
export { Withdraw } from './Withdraw'
export { Transfer } from './Transfer'
export { Affiliate } from './Affiliate'
export { Interest } from './Interest'
export { Redeem } from './Redeem'
export { Rebate } from './Rebate'
export { PersonalInfo } from './PersonalInfo'
export { Kyc } from './Kyc'
export { Settings } from './Settings'
export { SelfExclusion } from './SelfExclusion'
export { Vip } from './Vip'
export { profilePaths } from './menu'
